import { assert, it } from "@effect/vitest";
import { ThreadId } from "@t3tools/contracts";
import type { McpServerConfig, ResolvedMcpConfig } from "@t3tools/contracts";
import { Effect } from "effect";

import {
  claudeConfigFromResolved,
  codexTomlFromResolved,
  generatedMcpDir,
  mergeCodexToml,
  openCodeConfigFromResolved,
} from "./mcpTranslation.ts";

// ── Fixtures ─────────────────────────────────────────────────────

function makeConfig(servers: ReadonlyArray<McpServerConfig>): ResolvedMcpConfig {
  return {
    version: "test-hash-0000",
    resolvedAt: "2026-03-28T00:00:00.000Z",
    sourcePaths: [],
    servers: [...servers],
  } as ResolvedMcpConfig;
}

const stdioServer = {
  name: "my-server",
  transport: "stdio" as const,
  command: "node",
  args: ["server.js", "--port=3000"],
  // Keys intentionally in reverse-alphabetical order to verify sorting.
  env: { NODE_ENV: "production", API_KEY: "secret123" },
  enabled: true,
} as McpServerConfig;

const httpServer = {
  name: "remote-api",
  transport: "http" as const,
  url: "https://api.example.com/mcp",
  headers: {
    Authorization: "Bearer secret-token",
    "x-ref-api-key": "ref-123",
  },
  timeout: 2500,
  enabled: true,
} as McpServerConfig;

const sseServer = {
  name: "event-stream",
  transport: "sse" as const,
  url: "https://events.example.com/stream",
  enabled: false,
} as McpServerConfig;

// ── codexTomlFromResolved ────────────────────────────────────────

it.effect("codexTomlFromResolved generates TOML for stdio server with args and env", () =>
  Effect.sync(() => {
    const result = codexTomlFromResolved(makeConfig([stdioServer]));

    assert.include(result, "[mcp_servers.my-server]");
    assert.include(result, 'command = "node"');
    assert.include(result, 'args = ["server.js", "--port=3000"]');
    assert.include(result, "enabled = true");
    assert.include(result, "[mcp_servers.my-server.env]");
    assert.include(result, '"API_KEY" = "secret123"');
    assert.include(result, '"NODE_ENV" = "production"');

    // Env keys are sorted alphabetically regardless of insertion order.
    const apiKeyPos = result.indexOf('"API_KEY"');
    const nodeEnvPos = result.indexOf('"NODE_ENV"');
    assert.isBelow(apiKeyPos, nodeEnvPos);
  }),
);

it.effect("codexTomlFromResolved generates TOML for HTTP server with url", () =>
  Effect.sync(() => {
    const result = codexTomlFromResolved(makeConfig([httpServer]));

    assert.include(result, "[mcp_servers.remote-api]");
    assert.include(result, 'url = "https://api.example.com/mcp"');
    assert.include(result, "enabled = true");
    assert.notInclude(result, "command");
  }),
);

it.effect("codexTomlFromResolved sanitizes server names with special characters", () =>
  Effect.sync(() => {
    const server = { ...stdioServer, name: "my.server@v2" } as McpServerConfig;
    const result = codexTomlFromResolved(makeConfig([server]));

    assert.include(result, "[mcp_servers.my_server_v2]");
  }),
);

it.effect("codexTomlFromResolved includes generated header comment", () =>
  Effect.sync(() => {
    const result = codexTomlFromResolved(makeConfig([stdioServer]));

    assert.include(result, "# Generated by T3 Code.");
  }),
);

// ── mergeCodexToml ───────────────────────────────────────────────

it.effect("mergeCodexToml appends generated block after existing config", () =>
  Effect.sync(() => {
    const existing = '[model]\nname = "gpt-4"';
    const result = mergeCodexToml(existing, makeConfig([stdioServer]));

    assert.isTrue(result.startsWith('[model]\nname = "gpt-4"'));
    assert.include(result, "# Generated by T3 Code.");
    assert.include(result, "[mcp_servers.my-server]");
  }),
);

it.effect("mergeCodexToml replaces previously generated section on re-merge", () =>
  Effect.sync(() => {
    const existing = '[model]\nname = "gpt-4"';
    const firstMerge = mergeCodexToml(existing, makeConfig([stdioServer]));
    const secondMerge = mergeCodexToml(firstMerge, makeConfig([httpServer]));

    assert.include(secondMerge, '[model]\nname = "gpt-4"');
    assert.notInclude(secondMerge, "[mcp_servers.my-server]");
    assert.include(secondMerge, "[mcp_servers.remote-api]");
    const markerCount = secondMerge.split("# Generated by T3 Code.").length - 1;
    assert.equal(markerCount, 1);
  }),
);

it.effect("mergeCodexToml with empty existing config yields just generated block", () =>
  Effect.sync(() => {
    const result = mergeCodexToml("", makeConfig([stdioServer]));

    assert.isTrue(result.startsWith("# Generated by T3 Code."));
    assert.include(result, "[mcp_servers.my-server]");
  }),
);

// ── openCodeConfigFromResolved ───────────────────────────────────

it.effect("openCodeConfigFromResolved maps stdio server to local type", () =>
  Effect.sync(() => {
    const result = openCodeConfigFromResolved(makeConfig([stdioServer]));
    const parsed = JSON.parse(result) as Record<string, unknown>;

    assert.deepNestedInclude(parsed, { $schema: "https://opencode.ai/config.json" });
    const mcp = parsed.mcp as Record<string, Record<string, unknown>>;
    assert.deepEqual(mcp["my-server"], {
      type: "local",
      command: "node",
      args: ["server.js", "--port=3000"],
      env: { NODE_ENV: "production", API_KEY: "secret123" },
      enabled: true,
    });
  }),
);

it.effect("openCodeConfigFromResolved maps SSE server to sse type", () =>
  Effect.sync(() => {
    const result = openCodeConfigFromResolved(makeConfig([sseServer]));
    const parsed = JSON.parse(result) as { mcp: Record<string, Record<string, unknown>> };

    assert.equal(parsed.mcp["event-stream"]!.type, "sse");
    assert.equal(parsed.mcp["event-stream"]!.url, "https://events.example.com/stream");
    assert.equal(parsed.mcp["event-stream"]!.enabled, false);
  }),
);

it.effect("openCodeConfigFromResolved maps HTTP server to remote type", () =>
  Effect.sync(() => {
    const result = openCodeConfigFromResolved(makeConfig([httpServer]));
    const parsed = JSON.parse(result) as { mcp: Record<string, Record<string, unknown>> };

    assert.equal(parsed.mcp["remote-api"]!.type, "remote");
    assert.deepEqual(parsed.mcp["remote-api"]!.headers, {
      Authorization: "Bearer secret-token",
      "x-ref-api-key": "ref-123",
    });
    assert.equal(parsed.mcp["remote-api"]!.timeout, 2500);
  }),
);

// ── claudeConfigFromResolved ─────────────────────────────────────

it.effect("claudeConfigFromResolved maps stdio server to Claude mcpServers format", () =>
  Effect.sync(() => {
    const result = claudeConfigFromResolved(makeConfig([stdioServer]));
    const parsed = JSON.parse(result) as { mcpServers: Record<string, Record<string, unknown>> };

    assert.deepEqual(parsed.mcpServers["my-server"], {
      command: "node",
      args: ["server.js", "--port=3000"],
      env: { NODE_ENV: "production", API_KEY: "secret123" },
    });
  }),
);

it.effect("claudeConfigFromResolved maps remote server with explicit transport type", () =>
  Effect.sync(() => {
    const result = claudeConfigFromResolved(makeConfig([httpServer, sseServer]));
    const parsed = JSON.parse(result) as { mcpServers: Record<string, Record<string, unknown>> };

    assert.deepEqual(parsed.mcpServers["remote-api"], {
      type: "http",
      url: "https://api.example.com/mcp",
    });
    assert.deepEqual(parsed.mcpServers["event-stream"], {
      type: "sse",
      url: "https://events.example.com/stream",
    });
  }),
);

// ── generatedMcpDir ──────────────────────────────────────────────

it.effect("generatedMcpDir constructs correct per-session path", () =>
  Effect.sync(() => {
    const threadId = ThreadId.makeUnsafe("thread-42");
    const result = generatedMcpDir("/app/state", "codex", threadId);

    assert.equal(result, "/app/state/mcp/codex/thread-42");
  }),
);

it.effect("generatedMcpDir supports Claude session paths", () =>
  Effect.sync(() => {
    const threadId = ThreadId.makeUnsafe("thread-42");
    const result = generatedMcpDir("/app/state", "claudeAgent", threadId);

    assert.equal(result, "/app/state/mcp/claudeAgent/thread-42");
  }),
);
