import path from "node:path";

import type { McpServerConfig, ResolvedMcpConfig, ThreadId } from "@t3tools/contracts";

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function tomlArray(values: ReadonlyArray<string>): string {
  return `[${values.map((value) => tomlString(value)).join(", ")}]`;
}

function sanitizeName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_-]+/g, "_");
}

function tomlKey(value: string): string {
  return JSON.stringify(value);
}

const GENERATED_CODEX_TOML_MARKER = "# Generated by T3 Code.";

function codexServerBlock(server: McpServerConfig): string {
  const section = [`[mcp_servers.${sanitizeName(server.name)}]`];
  if (server.transport === "stdio") {
    section.push(`command = ${tomlString(server.command ?? "")}`);
    section.push(`args = ${tomlArray(server.args ?? [])}`);
  } else if (server.url) {
    section.push(`url = ${tomlString(server.url)}`);
  }
  section.push(`enabled = ${server.enabled ? "true" : "false"}`);
  if (server.env && Object.keys(server.env).length > 0) {
    section.push("");
    section.push(`[mcp_servers.${sanitizeName(server.name)}.env]`);
    for (const [key, value] of Object.entries(server.env).toSorted(([left], [right]) =>
      left.localeCompare(right),
    )) {
      section.push(`${tomlKey(key)} = ${tomlString(value)}`);
    }
  }
  return section.join("\n");
}

export function codexTomlFromResolved(config: ResolvedMcpConfig): string {
  const header = [
    GENERATED_CODEX_TOML_MARKER,
    "# This file contains the MCP overlay for a single provider session.",
  ];
  const blocks = config.servers.map(codexServerBlock);
  return [...header, "", ...blocks, ""].join("\n");
}

export function mergeCodexToml(existingConfig: string, config: ResolvedMcpConfig): string {
  const generatedBlock = codexTomlFromResolved(config);
  const markerIndex = existingConfig.indexOf(GENERATED_CODEX_TOML_MARKER);
  const baseConfig = markerIndex >= 0 ? existingConfig.slice(0, markerIndex) : existingConfig;
  const trimmedBase = baseConfig.trimEnd();
  if (trimmedBase.length === 0) {
    return generatedBlock;
  }
  return `${trimmedBase}\n\n${generatedBlock}`;
}

export function openCodeConfigFromResolved(config: ResolvedMcpConfig): string {
  const payload = {
    $schema: "https://opencode.ai/config.json",
    mcp: Object.fromEntries(
      config.servers.map((server) => [
        server.name,
        server.transport === "stdio"
          ? {
              type: "local",
              command: server.command,
              args: server.args ?? [],
              ...(server.env ? { env: server.env } : {}),
              enabled: server.enabled,
            }
          : {
              type: server.transport === "sse" ? "sse" : "remote",
              url: server.url,
              enabled: server.enabled,
            },
      ]),
    ),
  };
  return `${JSON.stringify(payload, null, 2)}\n`;
}

export function generatedMcpDir(
  stateDir: string,
  provider: "codex" | "cursor" | "opencode",
  threadId: ThreadId,
): string {
  return path.join(stateDir, "mcp", provider, String(threadId));
}
